name = "package-only-prereleases"
description = "The user requires any version of package `a` which only has prerelease versions available."

[root]
requires = ["a"]

[expected]
satisfiable = true
explanation = "Since there are only prerelease versions of `a` available, it should be installed even though the user did not include a prerelease specifier."

[expected.packages]
a = "1.0.0a1"

[packages.a.versions."1.0.0a1"]
