name = "package-only-prereleases-in-range"
description = "The user requires a version of package `a` which only matches prerelease versions but they did not include a prerelease specifier."

[root]
requires = ["a>0.1.0"]

[expected]
satisfiable = false
explanation = "Since there are stable versions of `a` available, prerelease versions should not be selected without explicit opt-in."

[packages.a.versions."0.1.0"]

[packages.a.versions."1.0.0a1"]
