name = "extra-incompatible-with-extra"
description = "Multiple optional dependencies are requested for the package, but they have conflicting requirements with each other."

[root]
requires = ["a[extra_b,extra_c]"]

[expected]
explanation = "Because both `extra_b` and `extra_c` are requested and they require incompatible versions of `b`, `a` cannot be installed."
satisfiable = false

[packages.b.versions."1.0.0"]

[packages.b.versions."2.0.0"]

[packages.a.versions."1.0.0".extras]
extra_b = ["b==1.0.0"]
extra_c = ["b==2.0.0"]
