name = "extra-required"
description = "Optional dependencies are requested for the package."

[root]
requires = ["a[extra]"]

[expected]
satisfiable = true

[expected.packages]
a = "1.0.0"
b = "1.0.0"

[packages.b.versions."1.0.0"]

[packages.a.versions."1.0.0".extras]
extra = ["b"]
