name = "transitive-yanked-and-unyanked-dependency"
description = "A transitive dependency has both a yanked and an unyanked version, but can only be satisfied by a yanked version"

[root]
requires = ["a", "b"]

[expected]
satisfiable = false
explanation = "Since the user did not explicitly select the yanked version, it cannot be used."

[packages.a.versions."1.0.0"]
requires = ["c==2.0.0"]

[packages.b.versions."1.0.0"]
requires = ["c>=1.0.0,<=3.0.0"]

[packages.c.versions."1.0.0"]

[packages.c.versions."2.0.0"]
yanked = true
