name = "no-build"
description = "Both wheels and source distributions are available, and the user has disabled builds."

[root]
requires = ["a"]

[expected]
satisfiable = true
explanation = "The wheel should be used for install"

[packages.a.versions."1.0.0"]

[resolver_options]
no_build = ["a"]
