name = "no-sdist-no-wheels-with-matching-platform"
description = "No wheels with matching platform tags are available, nor are any source distributions available"

[root]
requires = ["a"]

[expected]
satisfiable = false

[packages.a.versions."1.0.0"]
wheel_tags = ["py3-none-macosx_10_0_ppc64"]
sdist = false
