name = "specific-tag-and-default"
description = "A wheel for a specific platform is available alongside the default."

[root]
requires = ["a"]

[expected]
satisfiable = true

[packages.a.versions."1.0.0"]
wheel_tags = [
  "cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64",
  "py3-none-any",
]
