name = "post-greater-than-post"
description = "A greater-than version constraint should match a post-release version if the constraint is itself a post-release version."

[root]
requires = ["a>1.2.3.post0"]

[expected]
satisfiable = true
explanation = "The version '1.2.3.post1' satisfies the constraint '>1.2.3.post0'."

[expected.packages]
a = "1.2.3.post1"

[packages.a.versions."1.2.3.post0"]

[packages.a.versions."1.2.3.post1"]
