name = "post-equal-available"
description = "An equal version constraint should match a post-release version if the post-release version is available."

[root]
requires = ["a==1.2.3.post0"]

[expected]
satisfiable = true
explanation = "The version '1.2.3.post0' satisfies the constraint '==1.2.3.post0'."

[expected.packages]
a = "1.2.3.post0"

[packages.a.versions."1.2.3"]

[packages.a.versions."1.2.3.post0"]
