name = "local-transitive-conflicting"
description = "A dependency depends on a conflicting local version of a direct dependency."

[root]
requires = ["a", "b==2.0.0+foo"]

[expected]
satisfiable = false

[packages.a.versions."1.0.0"]
requires = ["b==2.0.0+bar"]

[packages.b.versions."2.0.0+bar"]

[packages.b.versions."2.0.0+foo"]
