name = "local-simple"
description = "A simple version constraint should not exclude published versions with local segments."

[root]
requires = ["a==1.2.3"]

[expected]
satisfiable = true
explanation = "The version '1.2.3+foo' satisfies the constraint '==1.2.3'."

[expected.packages]
a = "1.2.3+foo"

[packages.a.versions."1.2.3+foo"]
