name = "compatible-python-incompatible-override"
description = "The user requires a package which requires a compatible Python version, but they request an incompatible Python version for package resolution."

[root]
requires = ["a==1.0.0"]

[expected]
satisfiable = false

[packages.a.versions."1.0.0"]
requires_python = ">=3.10"
