name = "incompatible-python-compatible-override-available-no-wheels"
description = "The user requires a package which requires a incompatible Python version, but they request a compatible Python version for package resolution. There are only source distributions available for the package. The user has a compatible Python version installed elsewhere on their system."

[root]
requires = ["a==1.0.0"]

[expected]
satisfiable = true
explanation = "Since there is a compatible Python version available on the system, it should be used to build the source distributions."

[expected.packages]
a = "1.0.0"

[packages.a.versions."1.0.0"]
requires_python = ">=3.10"
wheel = false

[resolver_options]
python = "3.11"

[environment]
python = "3.9"
additional_python = ["3.11"]
