name = "incompatible-python-compatible-override"
description = "The user requires a package which requires a Python version greater than the current version, but they use an alternative Python version for package resolution."

[root]
requires = ["a==1.0.0"]

[expected]
satisfiable = true

[expected.packages]
a = "1.0.0"

[packages.a.versions."1.0.0"]
requires_python = ">=3.10"
