name = "incompatible-python-compatible-override-unavailable-no-wheels"
description = "The user requires a package which requires a incompatible Python version, but they request a compatible Python version for package resolution. There are only source distributions available for the package."

[root]
requires = ["a==1.0.0"]

[expected]
satisfiable = true
explanation = "Since there are no wheels for the package and it is not compatible with the local installation, we cannot build the source distribution to determine its dependencies. However, the source distribution includes static metadata, which we can use to determine dependencies without building the package."

[packages.a.versions."1.0.0"]
requires_python = ">=3.10"
wheel = false

[resolver_options]
python = "3.11"

[environment]
python = "3.9"
