name = "python-patch-override-patch-compatible"
description = "The user requires a package which requires a Python version with a patch version and the user provides a target version with a compatible patch version."

[root]
requires = ["a==1.0.0"]

[expected]
satisfiable = true

[expected.packages]
a = "1.0.0"

[packages.a.versions."1.0.0"]
requires_python = ">=3.8.0"

[resolver_options]
python = "3.8.0"

[environment]
python = "3.8.18"
