name = "python-less-than-current"
description = "The user requires a package which requires a Python version less than the current version"

[root]
requires = ["a==1.0.0"]

[expected]
satisfiable = true
explanation = "We ignore the upper bound on Python requirements"

[packages.a.versions."1.0.0"]
requires_python = "<=3.8"
